services:
  postgres:
    image: postgres:10-alpine
    container_name: 'postgres-server'
    environment:
      POSTGRES_DB: linktic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - linktic-network
  pgadmin-client:
    image: dpage/pgadmin4
    container_name: 'pgadmin-client'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_linktic
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '65432:80'
    volumes:
      - pgadmin-linktic-data:/var/lib/pgadmin
    networks:
      - linktic-network
  product-service:
    build:
      context: ./product
      dockerfile: Dockerfile
    container_name: 'product-service'
    environment:
      X_API_KEY: f72f7c71-6b82-4de1-b7a6-990970f34495
      POSTGRES_DATASOURCE_URL: jdbc:postgresql://postgres-server:5432/linktic
      POSTGRES_DB_USERNAME: postgres
      POSTGRES_DB_PASSWORD: postgres
      STOCK_SERVICE: http://stock-service:9090
      X_API_KEY_STOCK: 25adb200-6c1b-49ce-a3a7-87ee21ee2ac7
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - linktic-network
  stock-service:
    build:
      context: ./stock
      dockerfile: Dockerfile
    container_name: 'stock-service'
    environment:
      X_API_KEY: 25adb200-6c1b-49ce-a3a7-87ee21ee2ac7
      POSTGRES_DATASOURCE_URL: jdbc:postgresql://postgres-server:5432/linktic
      POSTGRES_DB_USERNAME: postgres
      POSTGRES_DB_PASSWORD: postgres
      PRODUCT_SERVICE: http://product-service:8080
      X_API_KEY_PRODUCT: f72f7c71-6b82-4de1-b7a6-990970f34495
    ports:
      - '9090:9090'
    depends_on:
      - postgres
      - product-service
    networks:
      - linktic-network
volumes:
  pgadmin-linktic-data:
networks:
  linktic-network:
    driver: bridge